### ISSUE TITLE
Static code analysis 

### ISSUE THREAD

**Issue by szucscintialia** [KeineKreativitat/CSharpVerbalExpressions#1]
using Visual Studio 2015 Code Analyzer

**Comment by naffannaffan** [comment]
I ran the Static code analyzer. No errors and no warnings were found.

**Comment by edani-eu** [comment]
I reviewed  @naffannaffan 's sollution. The given software do not has any probelms which could be found by the analyzer.

**Comment by edani-eu** [comment]
![img_6659](https://cloud.githubusercontent.com/assets/22350511/25192325/0f333394-2533-11e7-9436-e6523075d44d.JPG)

**Comment by micskeiz** [comment]
What ruleset have you used? Did you turn on all rules? If it really does not find any violations, it would be nice to try another tool, e.g. SonarQube can also check .NET code.
