### ISSUE TITLE
Integration of CI

### ISSUE THREAD

**Issue by szucscintialia** [KeineKreativitat/CSharpVerbalExpressions#2]
using AppVeyor

**Comment by mkrisz** [comment]
Missing namespaces Nuget packeges not found. :D

**Comment by szucscintialia** [comment]
https://www.appveyor.com/docs/nuget/#restoring-nuget-packages-before-build

**Comment by mkrisz** [comment]
Problem solved with restoring nugets. Build was successful. 
![build__succes](https://cloud.githubusercontent.com/assets/17525318/25195150/fe45bfde-253c-11e7-9bac-17079a31c463.png)

**Comment by naffannaffan** [comment]
I reviewed @mkrisz 's solution. The project was successfully built.
