### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by naffannaffan** [KeineKreativitat/CSharpVerbalExpressions#5]
Finding violations with the help of SonarQube

**Comment by szucscintialia** [comment]
I had a lot of difficulties with the integration SonarQube, but I finally successfully installed and used it. The analyzing ended with a little bit difference than VS Analyzer. 
![staticsonar](https://cloud.githubusercontent.com/assets/26093637/25499302/421306aa-2b8b-11e7-9fc1-b1dad0e76ad5.PNG)
We fixed the bug and code smells.

**Comment by szucscintialia** [comment]
![staticsonar2](https://cloud.githubusercontent.com/assets/26093637/25499932/6f6e93b0-2b8d-11e7-9990-35a67bc48b59.PNG)

**Comment by mkrisz** [comment]
I reviewed the SonarQube after the fixes. Everything looks fine.
