### ISSUE TITLE
Coverage measurement

### ISSUE THREAD

**Issue by naffannaffan** [KeineKreativitat/CSharpVerbalExpressions#6]
Measuring the coverage with the new tests

**Comment by naffannaffan** [comment]
Coverage with the already existing tests: 91.27%

![coverage_original](https://cloud.githubusercontent.com/assets/17600059/25497210/182d417c-2b84-11e7-9f2b-5b70d0a45b47.png)

Coverage with the newly written tests: 92.47%

![coverage_modified](https://cloud.githubusercontent.com/assets/17600059/25497209/182ceccc-2b84-11e7-890a-7d5bcd64eeab.png)

**Comment by szucscintialia** [comment]
I reviewed the test coverage, and I saw the same as the pictures above show.
